name: github pages

on:
  push:
    branches:
      - master
    # tags:
    #   - 'v*.*.*'

# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-git-tag
# $ # On the master branch
# $ git tag -a "v1.2.3" -m "Release v1.2.3"
# $ git push origin "v1.2.3"

# $ # After deployment
# $ git fetch origin
# $ git tag
# deploy-v1.2.3  # Tag on the gh-pages branch
# v1.2.3         # Tag on the master branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          extended: true

      - name: Build
        run: hugo # --minify

      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: swiftists/swiftists.github.io
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: master  # default: gh-pages
          publish_dir: ./public
          cname: www.swiftists.com
          force_orphan: false # This allows you to make your publish branch with only the latest commit.
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          # tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          # tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'